<?php

namespace PublicBundle\Repository;

/**
 * UserWhoCorrespRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWhoCorrespRepository extends \Doctrine\ORM\EntityRepository
{
}
